version: "3.8"
services:

    db_gitlab:
        image: mysql
        container_name: db_docker_gitlab
        restart: on-failure
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin_gitlab:
        image: phpmyadmin
        container_name: phpmyadmin_docker_gitlab
        restart: on-failure
        depends_on:
            - db_gitlab
        ports:
            - "8082:80"
        environment:
            PMA_HOST: db
        networks:
            - dev

    maildev_gitlab:
        image: maildev/maildev
        container_name: maildev_docker_gitlab
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: on-failure
        networks:
            - dev

    www_gitlab:
        build: php
        container_name: www_docker_gitlab
        ports:
          - "8080:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ../:/var/www
        restart: on-failure
        networks:
            - dev

networks:
    dev:

volumes:
    db-data: